<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>Vault_API_Sample_EntityAttributes</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Autodesk.Connectivity.LicenseWrapper">
      <HintPath>$(ProgramW6432)\Autodesk\Autodesk Vault 2027 SDK\bin\x64\core\Autodesk.Connectivity.LicenseWrapper.dll</HintPath>
    </Reference>
    <Reference Include="Autodesk.Connectivity.WebServices">
      <HintPath>$(ProgramW6432)\Autodesk\Autodesk Vault 2027 SDK\bin\x64\core\Autodesk.Connectivity.WebServices.dll</HintPath>
    </Reference>
    <Reference Include="Autodesk.Connectivity.WebServices.WCF">
      <HintPath>$(ProgramW6432)\Autodesk\Autodesk Vault 2027 SDK\bin\x64\core\Autodesk.Connectivity.WebServices.WCF.dll</HintPath>
    </Reference>
    <Reference Include="Autodesk.DataManagement.Client.Framework">
      <HintPath>$(ProgramW6432)\Autodesk\Autodesk Vault 2027 SDK\bin\x64\core\Autodesk.DataManagement.Client.Framework.dll</HintPath>
    </Reference>
    <Reference Include="Autodesk.DataManagement.Client.Framework.Vault">
      <HintPath>$(ProgramW6432)\Autodesk\Autodesk Vault 2027 SDK\bin\x64\core\Autodesk.DataManagement.Client.Framework.Vault.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="AdskIdentitySDK.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="AdskIdentitySDK.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="AdskLicensingSDK_10.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Ijwhost.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
